version: '3'

services:
  aspnetcore2:
    image: aspnetcore2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mssql
    links:
      - mssql:mssql   
      
  mssql:
    image: microsoft/mssql-server-linux  
    environment:
      SA_PASSWORD: "aspnetcore"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

